#!/bin/bash
NREG="-r16 -b5 -p"
TMPDIR=scratch
CHOW=`pwd`/chow
DEAD=-d
VALNUM=-v
LAZY=-z
CPROP=-c
GVAL="-g[-p]"
COALESCE=-s
CLEAN=-n
EXTRA="$DEAD $VALNUM $GVAL $LAZY $CPROP $COALESCE $DEAD"

mkdir $TMPDIR
pushd $TMPDIR

#fmm
#ctest /home/compiler/test/fmm/fmin/  -"{$CHOW $NREG}"
#ctest /home/compiler/test/fmm/zeroin/  -"{$CHOW $NREG}"
ctest /home/compiler/test/fmm/ $EXTRA -"{$CHOW $NREG}" $CLEAN

#spec
ctest /home/compiler/test/spec/matrix300/ $EXTRA -"{$CHOW $NREG}" $CLEAN
#ctest /home/compiler/test/spec/doduc/ $EXTRA -"{$CHOW $NREG}"

#spec95x
#ctest /home/compiler/test/spec95x/ $EXTRA -"{$CHOW $NREG}"

popd

