#!/bin/bash
#NREG="-r16"
NREG="-r16 -b5 -p"
TMPDIR=scratch
CHOW=`pwd`/chow
CLEAVE=`pwd`/cleave
FIX_UNDEF=-"{`pwd`/fix_undef}"
DEAD=-d
VALNUM=-v
LAZY=-z
CPROP=-c
GVAL="-g[-p]"
COALESCE=-s
CLEAN=-n
EXTRA="$DEAD $VALNUM $GVAL $LAZY $CPROP $COALESCE $DEAD"

mkdir $TMPDIR
pushd $TMPDIR

#fmm
#ctest /home/compiler/test/fmm/fmin/  -"{$CHOW $NREG}"
#ctest /home/compiler/test/fmm/seval/ -"{$CHOW $NREG}"
#ctest /home/compiler/test/fmm/solve/ -"{$CHOW $NREG}"
#ctest /home/compiler/test/fmm/urand/ -"{$CHOW $NREG}"
#ctest /home/compiler/test/fmm/zeroin/ -"{$CHOW $NREG}"
ctest /home/compiler/test/fmm/ $EXTRA -"{$CHOW $NREG}" $CLEAN

#spec
ctest /home/compiler/test/spec/doduc/ $EXTRA  -"{$CHOW $NREG}" $CLEAN
ctest /home/compiler/test/spec/matrix300/ $EXTRA -"{$CHOW $NREG}" $CLEAN
#ctest /home/compiler/test/spec/fpppp/ $EXTRA -"{$CHOW $NREG}" $CLEAN
ctest /home/compiler/test/spec/tomcatv/ $EXTRA -"{$CHOW $NREG}" $CLEAN

#spec95
ctest /home/compiler/test/spec95X/applu $EXTRA  -"{$CHOW $NREG}" $CLEAN
popd

